# =============================================================
#  invoke-m365-incident-response.ps1
#  Phase 8 — M365 Initial Security Triage
#  Enterprise-IT-Security-Operations-Toolkit
#  Author: Md Rahat Islam Anik
#  Description: Rapid evidence collection script for Microsoft
#  365 security investigations — user enumeration, license governance,
#  group review, and administrative role exposure triage.
# =============================================================

Connect-MgGraph -Scopes "User.Read.All","Directory.Read.All","Policy.Read.All","Organization.Read.All" -NoWelcome

$DateStamp = Get-Date -Format "yyyy-MM-dd"
$ReportRoot = Join-Path $PSScriptRoot "../reports"

Write-Host "`n🔐 Phase 8 — M365 Initial Security Triage" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray

# ── 1. User Enumeration ──────────────────────────────────────
Write-Host "`n📋 Collecting user evidence..." -ForegroundColor Cyan
$Users = Get-MgUser -Top 25 -Property DisplayName,Id,Mail,UserPrincipalName,AccountEnabled,CreatedDateTime
$UserReport = $Users | Select-Object DisplayName, UserPrincipalName, Mail, AccountEnabled, CreatedDateTime
$UserReport | Export-Csv "$ReportRoot/Phase8_User_Enumeration_$DateStamp.csv" -NoTypeInformation
Write-Host "   Users collected: $($Users.Count)" -ForegroundColor Green

# ── 2. License Governance ────────────────────────────────────
Write-Host "`n📋 Collecting license evidence..." -ForegroundColor Cyan
$Skus = Get-MgSubscribedSku
$LicenseReport = $Skus | Select-Object @{N="LicenseName";E={$_.SkuPartNumber}}, CapabilityStatus, ConsumedUnits, @{N="TotalUnits";E={$_.PrepaidUnits.Enabled}}
$LicenseReport | Export-Csv "$ReportRoot/Phase8_License_Governance_$DateStamp.csv" -NoTypeInformation
Write-Host "   License SKUs reviewed: $($Skus.Count)" -ForegroundColor Green

# ── 3. Security Group Review ─────────────────────────────────
Write-Host "`n📋 Collecting group evidence..." -ForegroundColor Cyan
$Groups = Get-MgGroup -Top 25 -Property DisplayName,Id,MailNickname,Description,GroupTypes,SecurityEnabled
$GroupReport = $Groups | Select-Object DisplayName, MailNickname, SecurityEnabled, Description
$GroupReport | Export-Csv "$ReportRoot/Phase8_Security_Group_Review_$DateStamp.csv" -NoTypeInformation
Write-Host "   Groups reviewed: $($Groups.Count)" -ForegroundColor Green

# ── 4. Administrative Role Review ────────────────────────────
Write-Host "`n📋 Collecting administrative role evidence..." -ForegroundColor Cyan
$Roles = Get-MgDirectoryRole
$RoleReport = $Roles | Select-Object DisplayName, Description, Id
$RoleReport | Export-Csv "$ReportRoot/Phase8_Admin_Role_Review_$DateStamp.csv" -NoTypeInformation
Write-Host "   Administrative roles reviewed: $($Roles.Count)" -ForegroundColor Green

# ── 5. Summary ───────────────────────────────────────────────
Write-Host "`n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "  PHASE 8 — INITIAL SECURITY TRIAGE SUMMARY" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "  Users Enumerated        : $($Users.Count)"
Write-Host "  License SKUs Reviewed   : $($Skus.Count)"
Write-Host "  Groups Reviewed         : $($Groups.Count)"
Write-Host "  Admin Roles Identified  : $($Roles.Count)"
Write-Host ""

$Summary = @"
====================================================
M365 INITIAL SECURITY TRIAGE SUMMARY
====================================================
Generated: $(Get-Date)
Phase: 8 — M365 Initial Security Triage

Users Enumerated     : $($Users.Count)
License SKUs         : $($Skus.Count)
Groups Reviewed      : $($Groups.Count)
Admin Roles          : $($Roles.Count)

Investigation Areas:
- User identity visibility and account status
- License governance and consumption
- Security and operational group review
- Administrative role exposure assessment
- Initial M365 security evidence collection for escalation

Generated By: Enterprise IT Security Operations Toolkit
Phase 8 — M365 Initial Security Triage
====================================================
"@

$Summary | Out-File "$ReportRoot/Phase8_Executive_Summary_$DateStamp.txt"

Write-Host "✅ Reports saved to: $ReportRoot" -ForegroundColor Green
Write-Host "`nDone!`n" -ForegroundColor Cyan
