# ==========================================================
# Enterprise IT Security Operations Toolkit
# Phase 5 - Microsoft 365 Security Investigation & Incident Response
# Author: Md Rahat Islam Anik
# ==========================================================

$ReportRoot = Join-Path $PSScriptRoot "../reports"
$DateStamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
New-Item -ItemType Directory -Force -Path $ReportRoot | Out-Null

Write-Host ""
Write-Host "===================================================="
Write-Host " PHASE 5 | M365 SECURITY INVESTIGATION TRIAGE"
Write-Host "===================================================="
Write-Host ""

Connect-MgGraph -Scopes "User.Read.All","Directory.Read.All","Policy.Read.All","Organization.Read.All" -NoWelcome

Write-Host "Collecting user evidence..."
$Users = Get-MgUser -Top 25
$Users | Select-Object DisplayName, Id, Mail, UserPrincipalName |
Export-Csv (Join-Path $ReportRoot "Phase5_User_Enumeration_$DateStamp.csv") -NoTypeInformation

Write-Host "Collecting license evidence..."
$Skus = Get-MgSubscribedSku
$Skus | Select-Object Id, AccountName, AppliesTo, CapabilityStatus, ConsumedUnits, SkuId |
Export-Csv (Join-Path $ReportRoot "Phase5_License_Governance_$DateStamp.csv") -NoTypeInformation

Write-Host "Collecting group evidence..."
$Groups = Get-MgGroup -Top 25
$Groups | Select-Object DisplayName, Id, MailNickname, Description |
Export-Csv (Join-Path $ReportRoot "Phase5_Security_Group_Review_$DateStamp.csv") -NoTypeInformation

Write-Host "Collecting administrative role evidence..."
$Roles = Get-MgDirectoryRole
$Roles | Select-Object DisplayName, Id, Description |
Export-Csv (Join-Path $ReportRoot "Phase5_Admin_Role_Review_$DateStamp.csv") -NoTypeInformation

$Summary = @"
====================================================
M365 SECURITY INVESTIGATION TRIAGE SUMMARY
====================================================

Generated:
$(Get-Date)

Users Reviewed:
$($Users.Count)

License SKUs Reviewed:
$($Skus.Count)

Groups Reviewed:
$($Groups.Count)

Administrative Roles Reviewed:
$($Roles.Count)

Investigation Areas:
- User identity visibility
- License governance
- Security and operational groups
- Administrative role exposure
- Initial Microsoft 365 incident response evidence

Generated By:
Enterprise IT Security Operations Toolkit
Phase 5 - Microsoft 365 Security Investigation & Incident Response

====================================================
"@

$Summary | Out-File (Join-Path $ReportRoot "Phase5_Executive_Summary_$DateStamp.txt")

Write-Host ""
Write-Host "Reports generated successfully."
Write-Host "Location: $ReportRoot"
Write-Host ""
